// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Miautrix.Mail.Persistence.Migrations;

public partial class AddFolderParentId : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<Guid>(
            name: "parent_id",
            table: "folders",
            type: "uuid",
            nullable: true);

        migrationBuilder.CreateIndex(
            name: "IX_folders_parent_id",
            table: "folders",
            column: "parent_id");

        migrationBuilder.AddForeignKey(
            name: "FK_folders_folders_parent_id",
            table: "folders",
            column: "parent_id",
            principalTable: "folders",
            principalColumn: "id",
            onDelete: ReferentialAction.Restrict);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "FK_folders_folders_parent_id",
            table: "folders");

        migrationBuilder.DropIndex(
            name: "IX_folders_parent_id",
            table: "folders");

        migrationBuilder.DropColumn(
            name: "parent_id",
            table: "folders");
    }
}
