// <auto-generated />
using Miautrix.Mail.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Miautrix.Mail.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20261001144022_CalendarEventRecurrenceFix")]
partial class CalendarEventRecurrenceFix
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}
