// <auto-generated />
using System;
using Miautrix.Mail.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Miautrix.Mail.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260918021252_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Miautrix.Mail.Domain.Tenant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Slug")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("slug");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.HasKey("Id");

                b.ToTable("tenants", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.TenantScopedEntityBase", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid")
                    .HasColumnName("tenant_id");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("idx_domains_tenant_id");

                b.ToTable((string)null);

                b.UseTpcMappingStrategy();
            });

        // Concrete tenant-scoped types. We only need table + base mapping
        // for design-time model building; runtime schema is driven by the
        // Up(MigrationBuilder) method in this migration.
        modelBuilder.Entity("Miautrix.Mail.Domain.Domain", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("domains", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.User", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("users", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.UserCredential", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("user_credentials", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.UserIdentity", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("user_identities", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.IdentityProvider", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("identity_providers", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.IdentityProviderGroup", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("identity_provider_groups", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.Role", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("roles", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.Permission", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("permissions", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.RolePermission", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("role_permissions", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.Membership", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("memberships", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.Session", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("sessions", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.RefreshToken", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("refresh_tokens", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.ApplicationPassword", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("application_passwords", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.ApiKey", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("api_keys", (string)null);
            });

        modelBuilder.Entity("Miautrix.Mail.Domain.Invitation", b =>
            {
                b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");
                b.ToTable("invitations", (string)null);
            });

        // NOTE: Remaining concrete types are intentionally omitted from this
        // minimal designer file. BuildTargetModel is used for migration
        // comparisons, but Up() contains the authoritative schema.

        modelBuilder.Entity("Miautrix.Mail.Domain.TenantScopedEntityBase", b =>
            {
                b.HasOne("Miautrix.Mail.Domain.Tenant", "Tenant")
                    .WithMany()
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Tenant");
            });

#pragma warning restore 612, 618
    }
}
