// <auto-generated />
using System;
using Miautrix.Mail.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Miautrix.Mail.Persistence.Migrations;

    [DbContext(typeof(AppDbContext))]
    [Migration("20260918034003_AddAuditLogColumns")]
    partial class AddAuditLogColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Miautrix.Mail.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.TenantScopedEntityBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_license_events_tenant_id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Alias", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("aliases", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.ApiKey", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.ApplicationPassword", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("application_passwords", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Attachment", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.AuditLog", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text")
                        .HasColumnName("details_json");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.BackupHistory", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("backup_history", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.BackupJob", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("backup_jobs", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Deploy", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("deploys", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.DkimKey", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("dkim_keys", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Domain", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.DomainDnsSetting", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("domain_dns_settings", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Folder", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Group", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.GroupMember", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.IdempotencyKey", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.IdentityProvider", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("identity_providers", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.IdentityProviderGroup", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("identity_provider_groups", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Invitation", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Job", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.JobDeadLetter", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("job_dead_letters", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.License", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("licenses", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.LicenseActivation", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("license_activations", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.LicenseEntitlement", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("license_entitlements", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.LicenseEvent", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("license_events", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.LicenseUsage", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("license_usage", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.MailFlowRule", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("mail_flow_rules", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Mailbox", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("mailboxes", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.MalwareVerdict", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("malware_verdicts", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Membership", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Message", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.MessageFlag", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("message_flags", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.MessageRecipient", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("message_recipients", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Permission", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.QuarantineItem", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("quarantine", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.RefreshToken", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Role", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.RolePermission", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SecurityEvent", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("security_events", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Session", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Setting", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SieveScript", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("sieve_scripts", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SmtpDeliveryAttempt", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("smtp_delivery_attempts", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SmtpQueueItem", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("smtp_queue", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SpamVerdict", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("spam_verdicts", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SystemEvent", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("system_events", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.User", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.UserCredential", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.UserIdentity", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("user_identities", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.TenantScopedEntityBase", b =>
                {
                    b.HasOne("Miautrix.Mail.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }

