// <auto-generated />
using System;
using Miautrix.Mail.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Miautrix.Mail.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Miautrix.Mail.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.TenantScopedEntityBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_license_events_tenant_id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Alias", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("TargetAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_address");

                    b.ToTable("aliases", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.ApiKey", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.ApplicationPassword", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("application_passwords", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Attachment", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.AuditLog", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text")
                        .HasColumnName("details_json");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.BackupHistory", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("backup_history", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.BackupJob", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("ArchivePath")
                        .HasColumnType("text")
                        .HasColumnName("archive_path");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.ToTable("backup_jobs", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Deploy", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("deploys", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.DkimKey", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain_name");

                    b.Property<string>("PrivateKeyPem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("private_key_pem");

                    b.Property<string>("PublicKeyPem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key_pem");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("selector");

                    b.ToTable("dkim_keys", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Domain", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("DkimPublicKey")
                        .HasColumnType("text")
                        .HasColumnName("dkim_public_key");

                    b.Property<string>("DkimSelector")
                        .HasColumnType("text")
                        .HasColumnName("dkim_selector");

                    b.Property<string>("DmarcRecord")
                        .HasColumnType("text")
                        .HasColumnName("dmarc_record");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SpfRecord")
                        .HasColumnType("text")
                        .HasColumnName("spf_record");

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.DomainDnsSetting", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("domain_dns_settings", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Folder", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("mailbox_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<long>("UidNext")
                        .HasColumnType("bigint")
                        .HasColumnName("uid_next");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint")
                        .HasColumnName("uid_validity");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Group", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.GroupMember", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("MemberAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_address");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.IdempotencyKey", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.IdentityProvider", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("identity_providers", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.IdentityProviderGroup", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("identity_provider_groups", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Invitation", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Job", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.JobDeadLetter", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("job_dead_letters", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.License", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("licenses", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.LicenseActivation", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("license_activations", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.LicenseEntitlement", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("license_entitlements", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.LicenseEvent", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("license_events", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.LicenseUsage", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("license_usage", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.MailFlowRule", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actions_json");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions_json");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.ToTable("mail_flow_rules", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Mailbox", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("QuotaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("quota_bytes");

                    b.Property<long>("UsedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("used_bytes");

                    b.ToTable("mailboxes", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.MalwareVerdict", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("engine");

                    b.Property<bool>("IsMalware")
                        .HasColumnType("boolean")
                        .HasColumnName("is_malware");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender");

                    b.Property<string>("ThreatName")
                        .HasColumnType("text")
                        .HasColumnName("threat_name");

                    b.ToTable("malware_verdicts", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Membership", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Message", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("BodyHtml")
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<string>("BodyText")
                        .HasColumnType("text")
                        .HasColumnName("body_text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flags");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("mailbox_id");

                    b.Property<string>("RawHeaders")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_headers");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint")
                        .HasColumnName("uid");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.MessageFlag", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flag");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.ToTable("message_flags", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.MessageRecipient", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.ToTable("message_recipients", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Permission", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.QuarantineItem", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_delivered");

                    b.Property<DateTimeOffset>("QuarantinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quarantined_at");

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_message");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reasons_json");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender");

                    b.Property<double>("SpamScore")
                        .HasColumnType("double precision")
                        .HasColumnName("spam_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.Property<DateTimeOffset?>("TrainedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trained_at");

                    b.ToTable("quarantine", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.RefreshToken", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Role", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.RolePermission", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SecurityEvent", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("security_events", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Session", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.Setting", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SieveScript", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("mailbox_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("sieve_scripts", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SmtpDeliveryAttempt", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<double?>("NextRetryDelaySeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("next_retry_delay_seconds");

                    b.Property<Guid>("QueueItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("queue_item_id");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.ToTable("smtp_delivery_attempts", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SmtpQueueItem", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_message");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.ToTable("smtp_queue", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SpamVerdict", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("DkimResult")
                        .HasColumnType("text")
                        .HasColumnName("dkim_result");

                    b.Property<string>("DmarcResult")
                        .HasColumnType("text")
                        .HasColumnName("dmarc_result");

                    b.Property<bool>("DnsblListed")
                        .HasColumnType("boolean")
                        .HasColumnName("dnsbl_listed");

                    b.Property<bool>("Greylisted")
                        .HasColumnType("boolean")
                        .HasColumnName("greylisted");

                    b.Property<bool>("IsSpam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_spam");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reasons_json");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender");

                    b.Property<string>("SpfResult")
                        .HasColumnType("text")
                        .HasColumnName("spf_result");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.ToTable("spam_verdicts", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.SystemEvent", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("system_events", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.User", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.UserCredential", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("algorithm");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.UserIdentity", b =>
                {
                    b.HasBaseType("Miautrix.Mail.Domain.TenantScopedEntityBase");

                    b.ToTable("user_identities", (string)null);
                });

            modelBuilder.Entity("Miautrix.Mail.Domain.TenantScopedEntityBase", b =>
                {
                    b.HasOne("Miautrix.Mail.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
